# Generated by Django 6.0.1 on 2026-01-16 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_question_remove_news_id_news_uid_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='questions_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='news',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='base.news'),
            preserve_default=False,
        ),
    ]
