# Generated by Django 6.0.1 on 2026-01-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_news_questions_generated_question_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='option_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_hi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
