# Generated by Django 6.0.1 on 2026-01-16 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_option_option_en_option_option_hi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptquestion',
            name='option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.option'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_hi',
            field=models.TextField(null=True),
        ),
    ]
